#define TICK_TIME 100000
#define SENSOR_QUEUE_NAME   "/sensor_queue"
#define ACTUATOR_QUEUE_NAME "/actuator_queue"
#define REFERENCE_QUEUE_NAME "/reference_queue"
#define REFERENCE2_QUEUE_NAME "/reference2_queue"
#define MONITOR_QUEUE_NAME "/monitor_queue"
#define PS_QUEUE_NAME "/ps_queue"
#define BACKUP_QUEUE_NAME "/backup_queue"
#define DIAG_QUEUE_NAME "/diag_queue"
#define DIAG2_QUEUE_NAME "/diag2_queue"
#define QUEUE_PERMISSIONS 0660
#define MAX_MESSAGES 200
#define MAX_MSG_SIZE 16
#define BUF_SIZE 5
#define T_MS 450
#define NS 1000000
#define PS_PRIO 3
#define DIAG_PRIORITY 1